- src/routes/auth/AuthRoutes.tsx
- src/routes/main/DiaryRoutes.tsx
- src/routes/main/MainRoutes.tsx
- src/routes/main/MypageRoutes.tsx
- src/routes/main/ReportRoutes.tsx
- 모든 하위 라우트에 notfoundpage 추가
- path="*"에 해당하면 notfoundpage 불러오도록 코드 수정
> 🐛 fix: 모든 route에 notfoundpage 처리

- src/api/LogoutApi.ts
- src/components/caffeine/CaffeineBottomSheet.tsx
- src/components/caffeine/CaffeineDetailForm.tsx
- src/components/common/BottomSheet.tsx
- src/components/common/SplashScreen.tsx
- src/components/report/PeriodFilterSelector.tsx
- src/pages/auth/KaKaoRedirectPage.tsx
-바텀시트 높이 버그 수정
- UI 개선
- 카카오 로그아웃 로직 연결
> 🐛 fix: 3차 버그 수정

- src/api/LogoutApi.ts
- src/api/apiClient.ts
- src/components/caffeine/CaffeineBottomSheet.tsx
- src/components/report/PeriodFilterSelector.tsx
- src/pages/auth/KaKaoRedirectPage.tsx
- src/pages/report/ReportPage.tsx
- '주차' 중복되는 초기화 변수 수정
- 날짜별 카페인 추가 기능 수정
- 카카오 로그아웃 테스트
> 🐛 fix: 4차 버그 수정

- src/components/caffeine/CaffeineDetailForm.tsx
- src/pages/diary/DiaryEditPage.tsx
> 🐛 fix: 버그 수정

- src/api/apiClient.ts
> 🐛 fix: 로그아웃 로직 재수정

- src/api/caffeineInfoApi.ts
- src/api/calendarApi.ts
- src/api/calendarListApi.ts
- src/api/dailyReportApi.ts
- src/api/healthInfoApi.ts
- src/api/monthlyReportApi.ts
- src/api/profileApi.ts
- src/api/weeklyReportApi.ts
- src/api/yearlyReportApi.ts
- staleTime 30초 -> 1분
- gcTime 1분 -> 5분
- refetchInterval 삭제
- 로그가 너무 자주 찍히는 문제 해결
> 🐛 fix: 캐시 리패치 전략 수정

- src/api/apiClient.ts
- src/components/diary/CaffeineList.tsx
- src/components/report/ReportMessage.tsx
- src/utils/RequireAuth.tsx
- 리포트 결과 없을 때 기본 화면으로 보여주기
- 로컬스토리지 아이템 삭제 처리 강화
> 🐛 fix: 리포트 결과 요약 분기 처리

- src/components/common/TwoOptionToggle.tsx
- src/components/mypage/HealthInfoEditor.tsx
- src/components/mypage/ProfileCard.tsx
- src/components/mypage/SettingMenu.tsx
- src/components/onboarding/Step1.tsx
- src/components/onboarding/Step2.tsx
- src/data/cafe_drinks.json
- src/pages/mypage/MypagePage.tsx
- 컴포넌트 분리 진행(SectionCard, TwoOptionToogleGroup)
- 화면에서 동일하게 보여지는지 확인, 해당 value가 맞게 변경되지는지 콘솔로 확인, 이후 테스트코드 작성 예정
> Refactor: 컴포넌트 분리

- src/App.tsx
- src/components/diary/CaffeineCalendar.tsx
- src/components/diary/CaffeineList.tsx
- src/components/home/DailyCaffeineRemain.tsx
- src/pages/diary/DiaryPage.tsx
- src/utils/date.ts
- utils 폴더 아래 시간 포맷 형식 formatDate 함수를 분리하였다.
> ♻️ refactor: 날짜 util 함수 만들기

- src/pages/diary/DiaryEditPage.tsx
- 다이어리 수정 페이지에 카페인 함량이 안보이는 버그 수정
> 🐛 fix: 다이어리 수정 페이지 버그 수정

- src/pages/coffeechat/CoffeeChatDetailPage.tsx
- src/pages/coffeechat/GroupChatPage.tsx
- src/stores/webSocketStore.ts
- api 변동에 따른 커피챗 참여 여부 로직 수정
- 참여 여부에 따른 stomp 연결 상태 로직 수정
- 참여 여부를 memberId 받아서 `GroupChatPage.tsx`로 넘김
- `webSocketStore.ts`의 이미 연결된 경우 연결 상태 isConnected 처리
- 개발자 도구 콘솔에서 memberId 확인
> ✨ feat: 커피챗 참여 여부 api 연결

- src/api/coffeechat/coffeechat.dto.ts
- src/api/coffeechat/coffeechatMessageApi.ts
- src/components/coffeechat/ChatMessage.tsx
- src/pages/coffeechat/GroupChatPage.tsx
- src/stores/webSocketStore.ts
- useInfiniteQuery로 과거 메시지 요청
- IntersectionObserver로 스크롤 감지해서 무한 스크롤 구현
- 백엔드와 테스트 예정
> ✨ feat: 채팅 무한 스크롤 구현

- src/api/coffeechat/coffeechatApi.ts
- src/components/coffeechat/GroupMemberMenu.tsx
- src/components/common/Header.tsx
- src/layout/PageLayout.tsx
- 커피챗 삭제 api 연동
- 그룹 채팅방 드로어에 방장인 경우 '커피챗 삭제하기' 버튼 보여짐
- 헤더와 드로어 props 수정
> ✨ feat: 커피챗 삭제 api 연동

- src/api/coffeechat/coffeechatMessageApi.ts
- src/components/coffeechat/ChatMessages.tsx
- src/pages/coffeechat/CoffeeChatDetailPage.tsx
- src/pages/coffeechat/GroupChatPage.tsx
- 채팅 내역 렌더링 순서 수정
- 채팅방 삭제 버그 수정
- 과거 채팅 내역 불러오기 api 옵셩 수정
- 채팅 렌더링 순서 -> deque 형식으로 js 배열 로직 처리
> 🐛 fix: 그룹채팅방 버그 수정

- src/components/home/TodayCoffeeChatSection.tsx
> 💄 design: 커피챗 아이콘 수정

- src/data/cafe_drinks.json
> 🐛fix: 카페라떼 관련 오류 데이터 수정

- index.html
- src/index.css
- 폰트 최적화를 통한 렌더링 성능 개선
- 폰트 @import css를 <link>로 변경
- `rel=preload` 추가
- 가변 다이나믹 서브셋 적용
- 로컬에서 성능 측정을 했지만 이후 main으로 할 때 개발 서버와 운영 서버 둘 다 성능 측정을 할 예정입니다.
- devTools의 network, performance, lighthouse 사용
> [PEFORMANCE] 폰트 최적화

- src/components/event/GoogleFormLinkButton.tsx
- src/components/home/EventCoffeeChat.tsx
- src/components/home/containers/TodayCoffeeChatContainer.tsx
- src/pages/coffeechat/coffeechatdetailpage/CoffeeChatDetailContainer.tsx
- src/pages/coffeechat/coffeechatdetailpage/CoffeeChatDetailPageUI.tsx
- src/pages/coffeechat/groupchatpage/GroupChatContainer.tsx
- 이벤트 커피챗 기능 추가
- 커피챗 나가기 버그 수정
- `GoogleFormLinkButtom.tsx`으로 구글폼 컴포넌트 구현
- 이벤트 커피챗 id에 해당하는 커피챗은 `EvenetCoffeechat.tsx`로 렌더링
- 커피챗 나가기 비정상적 동작 -> sendMessage 이후 나가기 api 요청으로 변경
- 운영 서버, 개발 서버의 이벤트 커피챗 id가 달라서 개발 서버에서는 정상적으로 동작하지 않을 수 있습니다.
- 브라우저로 확인
> [FEAT] 이벤트 커피챗 추가

- src/pages/auth/OnboardingPage.tsx
- src/pages/common/EventPage.tsx
> release v3.0.3

- src/components/review/ViewReviewForm.tsx
- v3 QA에 따라 후기 작성 보기에서 `멤버`와 `참여 후기` 섹션 순서 교체
- `ViewReviewForm.tsx`의 두 섹션 코드 수정
- 브라우저 확인
> [FIX] 후기 작성 보기 UI 수정

- src/components/coffeechat/JoinCoffeeChatModal.tsx
- src/pages/coffeechat/coffeechatdetailpage/CoffeeChatDetailContainer.tsx
- src/pages/coffeechat/coffeechatdetailpage/CoffeeChatDetailPageUI.tsx
> release v3.0.5

- src/components/review/ReviewCard.tsx
- `CoffeeChatIcon.png` 이미지 포맷 지정
- devTools network 탭에서 확인
> [PERFORMANCE] 이미지 최적화 2단계(3차)
